version: "3.9"
services:
  couchdb:
    build: .
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=admin  # please please please replace this with a secure password
      - BBRF_PASSWORD=bbrf # please please please replace this with a secure password
  proxy:
    image: nginx
    ports:
     # - "80:80"
     - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./docker-entrypoint.d/:/docker-entrypoint.d/
    environment:
     - NGINX_HOST=*
     - NGINX_PORT=80
    depends_on:
      - couchdb